% -*- mode: texinfo; coding: latin-1; ispell-local-dictionary: "deutsch8" -*-
\def\niceracronym#1{#1}
%\def\rmdefault{ppl}\def\ne{\mathrel{\not{}\mskip-8mu=}}\input pstexinfo
\input texinfo
@c@let@acronym@niceracronym

@c======================================================================@>
@c    felo-de.texi - Deutsche Anleitung zum Felo-Programm               @>
@c    Copyright 2006 Torsten Bronger                                    @>
@c                   <bronger@physik.rwth-aachen.de>                    @>
@c                                                                      @>
@c  This program may be distributed and/or modified under the           @>
@c  conditions of the MIT licence with the following constraint:        @>
@c  If you copy or distribute a modified version of this Software, the  @>
@c  entire resulting derived work must be given a different name and    @>
@c  distributed under the terms of a permission notice identical to     @>
@c  this one.                                                           @>
@c                                                                      @>
@c  Permission is hereby granted, free of charge, to any person         @>
@c  obtaining a copy of this software and associated documentation      @>
@c  files (the ``Software''), to deal in the Software without           @>
@c  restriction, including without limitation the rights to use, copy,  @>
@c  modify, merge, publish, distribute, sublicense, and/or sell copies  @>
@c  of the Software, and to permit persons to whom the Software is      @>
@c  furnished to do so, subject to the following conditions:            @>
@c                                                                      @>
@c      The above copyright notice and this permission notice shall be  @>
@c      included in all copies or substantial portions of the           @>
@c      Software.                                                       @>
@c                                                                      @>
@c      If you copy or distribute a modified version of this Software,  @>
@c      the entire resulting derived work must be given a different     @>
@c      name and distributed under the terms of a permission notice     @>
@c      identical to this one.                                          @>
@c                                                                      @>
@c  The Software is provided ``as is'', without warranty of any kind,   @>
@c  express or implied, including but not limited to the warranties of  @>
@c  merchantability, fitness for a particular purpose and               @>
@c  noninfringement.  In no event shall the authors or copyright        @>
@c  holders be liable for any claim, damages or other liability,        @>
@c  whether in an action of contract, tort or otherwise, arising from,  @>
@c  out of or in connection with the Software or the use or other       @>
@c  dealings in the Software.                                           @>
@c======================================================================@>

@c %**start of header
@setchapternewpage odd
@setfilename felo-de.info

@set VERSION 1.0
@set SHORTVERSION 10

@settitle Felo @value{VERSION}
@documentencoding ISO-8859-1
@documentlanguage de
@c %**end of header

@defindex kw
@syncodeindex kw cp

@macro HTML {}
@acronym{HTML}
@end macro

@macro RSS {}
@acronym{RSS}
@end macro

@macro PDF {}
@acronym{PDF}
@end macro

@macro PNG {}
@acronym{PNG}
@end macro

@macro RWTH {}
@acronym{RWTH}
@end macro

@macro s {}
@tex
@kern0.1667em%
@end tex
@end macro

@macro xmarksthespot {}
@tex
`@math{@times{}}'@ignorespaces
@end tex
@ifnottex
`x'@c
@end ifnottex
@end macro

@copying
Die Anleitung erläutert das Felo-Programm, mit dem eine objektive
Einschätzung der Fechtstärke von Fechtern möglich ist.  Es lehnt sich
dabei an das Elo-System beim Schach an.

Copyright @copyright{} 2006 Torsten Bronger
@t{<}@email{bronger@@physik.rwth-aachen.de}@t{>}.


@quotation
Diese Dokumentation ist freie Software; du kannst sie frei verteilen
oder modifizieren unter den Bedingungen der @acronym{MIT}-Lizenz.
@end quotation
@end copying

@finalout
@titlepage
@title Felo
@subtitle Objektive Fechtstärken beim Fechten
@subtitle Version @value{VERSION}
@sp 2
@image{felo-logo,10cm,,Felo logo}
@author Torsten Bronger
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@dircategory Miscellaneous
@direntry
* Felo: (Felo).           Das Felo-Zahlen-Programm
@end direntry

@iftex
@hyphenation{ca-ta-logue ca-ta-logues}
@end iftex


@ifnottex
@node Top
@top Das Felo-Programm zum objektiven Einschätzen der Spielstärke beim Fechten

@uref{http://felo.sourceforge.net,Felo} berechnet Felo-Zahlen für
Fechter.  Felo-Zahlen geben einen guten Eindruck von der Spielstärke
eines Fechters.  Das Programm ist gedacht für Fechtgruppen, um einen
weiteren Trainings-Anreiz zu schaffen, oder sogar um ein Kriterium für
Setzlisten oder Teamauswahl zu haben.

Einigermaßen zuverlässige Zahlen sind schon bei einer handvoll Fechter
nach einigen Trainingstagen möglich.  Nach oben die die Grenze nahezu
offen.  Es müssen nur die Ergebnisse von allen Gefechten eingesammelt
und eingegeben werden; die Berechnung selber geht sehr schnell.

Das Programm ist bequem über eine grafische Oberfläche zu bedienen.  Für
die Bastler unter euch ist es außerdem möglich, nur den Kern des
Felo-Programms zu benutzen und ein eigenes Programm drumherum zu
stricken, um z.@s{}B. eine Webseite automatisch zu aktualisieren.

Das Programm ist freie Software, was insbesondere bedeutet, daß es
kostenlos verteilt wird und jeder den Quellcode haben und verändern
darf.  Der Autor freut sich als Gegenleistung über eine Postkarte, die
man ihm schickt (T.@tie{}Bronger, Lochnerstraße@tie{}7,
52064@tie{}Aachen; bitte schließe die RWTH-Fechter in deine Grüße ein,
wir freuen uns, von anderen Fechtgruppen zu hören).  Außerdem kann man,
falls man Bock hat und eine Fremdsprache spricht, helfen, Felo in
@uref{http://felo.sourceforge.net/translations.html,andere Sprachen zu
übersetzen}.

@menu
* Schnellstart::                Für die Ungeduldigen.
* Felo-Zahlen::                 Was sind Felo-Zahlen?
* Benutzen des Programms::      Wie man Felo-Zahlen bestimmt.
* Installation::                Installation von Felo.
* Felo-Zahlen -- etwas Hintergrund::  Erklärungen für wirklich
                                  Interessierte.
@end menu
@end ifnottex

@ifhtml
Diese Anleitung existiert auch als
@uref{http://felo.sourceforge.net/felo-de/,Sammlung von @HTML{}-Dateien} (auch in
@uref{http://felo.sourceforge.net/felo-de-handbuch.zip,gezippter Form}), als
@uref{http://felo.sourceforge.net/felo-de.html,einzelne @HTML{}-Seite} und als
@uref{http://felo.sourceforge.net/felo-de.pdf,@PDF{}-Datei}.
@end ifhtml

@c Output the table of the contents at the beginning.
@contents

@ifnottex
@insertcopying
@end ifnottex


@node Schnellstart
@chapter Schnellstart

@enumerate
@item
Lade @uref{http://downloads.sourceforge.net/felo/Felo-1.0.exe,Felo}
herunter und installiere es.

@item
Starte Felo.  Im Editorfenster tippst du einige Gleichheitszeichen und
dahinter die Fechter deiner Gruppe ein.  Immer Name, Tabstopp @key{Tab},
und dann deren (von @emph{dir}) geschätzte Anfangszahl:

@example
====================================
Alexander          1600
Julia              1400
Christian          1600
Jens               1300
...
@end example

@noindent
Die geschätzten Anfangszahlen sollten sich so zwischen 1300 und
1800@tie{}Punkten bewegen.  Je größer, desto besser der Fechter.

@item
Tippe nochmal ein paar Gleichheitszeichen in eine Zeile und gib dahinter
die Gefechte ein:

@example
====================================
2006-05-01      Alexander -- Julia   5:3
                Alexander -- Jens    5:1
                Julia -- Jens        5:3
                Julia -- Alexander   1:5
                Jens -- Alexander    2:5
                Julia -- Jens        5:10
                Alexander -- Jens    9:10

2006-05-08      Christian -- Jens    10:5
                ...
@end example

@noindent
Dabei müssen die Tage, die Paarungen und die Ergebnisse mit Tabstopps
@key{Tab} voneinander getrennt werden.  Speichere die Datei jetzt ab,
z.@s{}B. unter @emph{florett.felo}.

@item
Klicke im Menü auf ,,Berechnen`` -- ,,Felo-Zahlen berechnen``.  Es
öffnet sich ein Fenster mit den Felo-Zahlen der Fechter, die sich nach
allen bisher eingegebenen Gefechten ergeben.  Nach dem nächsten
Trainigstag hängst du die neuen Ergebnisse unten an und bekommst die
dann aktuellen Felo-Zahlen.  Und so weiter.
@end enumerate


@node Felo-Zahlen
@chapter Was sind Felo-Zahlen?

@uref{http://felo.sf.net,Felo-Zahlen} sind eine hinreißende neue
Methode, momentane Spielstärken von Fechtern objektiv und unbestechlich
einzuschätzen, ohne die lästige Glückskomponente, wie sie in K.O.-Runden
oder Einzelgefechten üblich ist.  Die Felo-Zahl wird nach jedem
Trainingstag neu berechnet.  Sie ist also immer da und paßt sich stets
an, wenn man sich verbessert oder verschlechtert.  So hat der Fechter
einen Eindruck davon, wie gut er momentan ist.  Innerhalb einer Gruppe
sind Felo-Zahlen sehr akkurat, aber im Prinzip kann man sie sogar global
vergleichen.

Die Idee dahinter ist nicht neu.  Inspiriert ist das ganze von den
Elo-Zahlen beim Schachspiel.  Sie werden seit 35@tie{}Jahren benutzt, um
die Schach-Weltrangliste aufzustellen, und sie funktionieren dort
prächtig.  Nicht nur, daß sie eine plausible Rangfolge ermöglichen, sie
lassen sogar sehr präzise Aussagen über Siegchancen bei anstehenden
Matches zu.

Die Elo-Zahlen sind in der Folgezeit erfolgreich auf Go und
Nationalmannschafts-Fußball übertragen worden.  Mit dem Felo-Programm
kann man sie nun auch im Fechten benutzen.  ,,Felo`` ist also nichts
anderes als ,,Fechter-Elo``.  Im Gegensatz zu den anderen Elo-Sportarten
berücksichtigen die Felo-Zahlen auch den Spielstand.  Ein 15:14 geht
also anders in die Rechnung ein als ein 15:0.  Klingt
selbstverständlich, aber beim Schach gibt's nur gewinnen, verlieren und
unentschieden.

Die Felo-Zahlen bewegen sich in typischen Uni-Fechtgruppen zwischen 1300
und 1800 Punkten.  Hier eine Übersicht, wie die Felo-Zahl zu bewerten
ist:

@table @asis
@item ab 2500
Fechten wie ein junger Gott

@item ab 2400
Internationale Meister

@item ab 2200
Nationale Meister

@item ab 1800
sehr gute Vereinsspieler

@item ab 1600
starke Freizeitspieler

@item ab 1400
Schwache und durchschnittliche Freizeitspieler

@item ab 1300
Anfänger

@item 1200
untere rechnerische Grenze
@end table

Die Tabelle ist mit Vorsicht zu genießen, weil die Erfahrungen mit
Felo-Zahlen bislang noch nicht groß ist.

@menu
* Hilfe bekommen::              Bei Fragen, Wünschen und Problemen ...
* Danksagungen::                
@end menu


@node Hilfe bekommen
@section Hilfe bekommen

Wenn man Probleme oder Fragen zum Programm Felo oder den Felo-Zahlen
auftauchen, die diese Anleitung nicht beantworten kann, gibt es folgende
Anlaufstellen:

@table @uref
@item http://sourceforge.net/forum/forum.php?forum_id=638727
Ein Web-basiertes Forum zum Felo-Programm.

@item https://lists.sourceforge.net/lists/listinfo/felo-general
Die Felo-Mailingliste.  Hier wird ausdrücklich nicht nur dieses Programm
besprochen, sondern auch das Konzept der Felo-Zahlen als solches.
Übrigens kann man diese Mailingliste alternativ als sogenannte
@uref{http://dir.gmane.org/gmane.sports.fencing.felo-rating,Newsgruppe}
beziehen (inklusive der Möglichkeit von Web-Interface und RSS-Feed).

@item http://sourceforge.net/tracker/?group_id=183431&atid=905214
Hier kann man Fehler, die man im Felo-Programm und seiner Dokumentation
findet, melden.  Fehler, die andere schon gemeldet haben, kann man hier
einsehen.

@item http://sourceforge.net/tracker/?atid=905217&group_id=183431
Hier kann man Verbesserungsvorschläge einreichen.

@end table

Alle diese Dinge laufen auf Englisch.  Es wird vermutlich niemandem bei
einem nicht-Englischen Beitrag der Kopf abgebissen (von mir ganz sicher
nicht), aber man sollte sich schon dran halten.

Außerdem ist bronger@@physik.rwth-aachen.de die Email-Adresse des
aktuellen Betreuers von Felo.  Falls du also Mit-Entwickler werden
möchtest@tie{}@dots{}


@node Danksagungen
@section Danksagungen

Im großen und ganzen ist Felo bislang -- seufz -- das Projekt eines
Einzelkämpfers.  (Bitte kein Mitleid, es hat natürlich Spaß gemacht.)
Allerdings hatte ich schon ein bißchen Hilfe.

@table @asis
@item Marc Ensenbach
hat mir als gelernter Mathematiker bestätigt, daß das was ich mache,
weitgehend sinnvoll ist, und gleichzeitig Fehler gefunden, die ich
dann ausgemerzt habe.

@item Stefan Mainka
hat fleißig all unsere Fechtergebnisse aufgeschrieben, lange bevor es
Felo gab.  Für mich war das natürlich ein Glücksfall, weil ich so recht
schnell das Konzept testen konnte.  Ich danke auch der ganzen
RWTH-Fechtgruppe, weil niemand Einspruch erhoben hat, als ich diese doch
recht personenbezogenen Daten ins (interne) Web stellen wollte.

@c @item Roberto Pereira
@c hat das Programm ins Spanische übersetzt.
@end table


@node Benutzen des Programms
@chapter Benutzen des Programms

@section Die Felo-Datei -- Fechter und Gefechte

Starte das Programm Felo.  Es öffnet sich das Programmfenster mit einer
leeren Editor-Fläche.  Darin kannst du die Felo-Datei eingeben.  Die
Felo-Datei enthält alle Fechter und Gefechte einer Fechtgruppe, für die
die Felo-Zahlen ausgerechnet werden sollen.  Mit der Zeit wächst die
Felo-Datei mehr und mehr, weil die neuen Gefechte unten angehängt
werden.

Zur Zeit weißt du vermutlich noch nicht, wie eine Felo-Datei überhaupt
auszusehen hat.  Kein Problem.  Wähle im Menü ,,Datei`` den ersten Punkt
,,Neu`` aus.  Es wird dann eine Beispiel-Datei in den Editor geladen:

@image{felo-screen-1-de,10cm,,Die Beispiel-Felo-Datei}

Eine Felo-Datei besteht aus drei Teilen:

@enumerate
@item
Parameter

@item
Fechterliste

@item
Gefechte

@end enumerate

@noindent
Diese drei Teile sind durch Linien, die aus Gleichheitszeichen bestehen,
voneinander getrennt (die Anzahl der Gleichheitszeichen ist egal).  Im
einzelnen bedeuten die drei Teile folgendes:

@table @strong
@item Parameter
Parameter können der Name der Gruppe sein (z.@s{}B. für die
Unterscheidung der Waffengattungen und/oder Geschlechter innerhalb eines
Vereins), oder Angaben, die das Aussehen der Plots beeinflussen, sowie
Einstellungen bezüglich der mathematischen Berechnung der Felo-Zahlen.

Jeder Parameter steht in einer eigenen Zeile mit zwei Spalten.  In der
ersten Spalte ist der Name des Parameters (z.@s{}B. ,,Gruppenname``) und
in der zweiten Spalte der Wert dieses Parameters (z.@s{}B. ,,Florett``).

Im Prinzip kann man den Parameter-Teil einfach leer lassen, dann werden
die Vorgabe-Werte genommen, die in den meisten Fällen ausreichen.
Ansonsten werde ich auf die Parameter später nochmal detailliert
eingehen, @pxref{Liste aller Parameter}.

@item Fechterliste
Hier muß man alle Fechter der Gruppe aufführen, einen pro Zeile.  Auch
in diesem Teil gibt es zwei Spalten, nämlich für den Namen und für die
Anfangs-Felo-Zahl.  Wie man auf die kommt, erkläre ich später,
@pxref{Bestimmen von Anfangs-Felo-Zahlen}.

Wichtig ist, daß für Fechter, deren Namen in Klammern @samp{(...)}
stehen, keine Felo-Zahlen berechnet werden.  Das ist für Fechter
gedacht, die eben nicht interessiert sind an ihrer Felo-Zahl und auch
nicht irgendwo genannt werden wollen.  Trotzdem sollten ihre Gefechte
notiert werden (es sei denn, sie haben etwas dagegen), denn es hilft,
die Felo-Zahlen der anderen genauer zu berechnen.

@item Gefechte
Hier werden die Gefechte notiert, eines pro Zeile (Leerzeilen sind
erlaubt, wie auch sonst in einer Felo-Datei).  Jede Zeile besteht aus
drei Spalten, nämlich dem Datum, der Paarung und dem Ergebnis.  Das
Datum @emph{muß} in der Form @samp{JJJJ-MM-TT} angegeben werden, also
erst das Jahr, dann der Monat, dann der Tag, alles durch Bindestriche
getrennt.

Die Paarung muß in der Form @samp{Erster -- Zweiter} angegeben werden,
d.@s{}h.@: die Fechter werden durch zwei Bindestriche voneinander
getrennt.
@end table


@cartouche
@strong{Wichtig: Spalten werden in Felo-Dateien durch Tabstopps
@key{Tab} voneinander getrennt.  Wieviele, ist egal, Hauptsache
mindestens einer.}
@end cartouche

Wenn man möchte, kann man an beliebigen Stellen in der Felo-Datei
Kommentare einfügen, die vom Programm ignoriert werden.  So kann man
z.@s{}B. Gefechte markieren, deren Ergebnis man nochmal überprüfen
möchte, oder Stellen, wo noch Gefechte fehlen, weil einem die Ergebnisse
noch nicht vorlagen.  Zeilen, in denen man solche Kommentare einstreut,
müssen mit einem @samp{#} beginnen -- Felo schert sich dann um diese
Zeilen genausowenig wie um Zeilen, in denen gar nichts steht.

@menu
* Zusatz-Infos zum Eingeben von Gefechten::
* Felo-Zahlen berechnen::
* Felo-Zahlen ins Internet stellen::
* Bestimmen von Anfangs-Felo-Zahlen::
* Liste aller Parameter::
@end menu


@node Zusatz-Infos zum Eingeben von Gefechten
@section Zusatz-Infos zum Eingeben von Gefechten

Die meiste Zeit in Felo wird man Gefechte eingeben.  Dabei gibt es ein
paar Dinge zu beachten.  Im Prinzip ist das Format eines Gefechts sehr
simpel:

@example
2006-12-24      Christkind -- Gabriel           15:3
@end example

@noindent
Die drei Spalten werden dabei durch Tabstopps @key{Tab} getrennt.

Bei Gefechten eines Tages muß bloß das erste Gefecht mit dem Datum
versehen sein.  Damit kann man die Liste etwas übersichtlicher
gestalten:

@example
2006-05-01      Anakin -- Elmer         5:3
                Anakin -- Wile Coyote   5:1
                Elmer -- Wile Coyote    5:3
                Elmer -- Anakin         1:5
                Wile Coyote -- Anakin   2:5
                Elmer -- Wile Coyote    5:10
                Anakin -- Wile Coyote   9:10
@end example

@unnumberedsubsec Tagesindex

Wenn man weiß, in welcher Reihenfolge die Gefechte an einem bestimmten
Tag gefochten wurden, kann man sehr penibel sein und noch einen
Tagesindex an das Datum hängen, bei@tie{}1 beginnend:

@example
2006-12-07.1    Peter -- Jens           15:12
           2    Peter -- Julia          13:15
           3    Julia -- Jens           8:15
           4    Jens -- Max             10:15
@end example

@noindent
(Gefechte ohne Index bekommen intern allesamt den Index@tie{}`@math{0}'
vom Programm zugewiesen.)

@c @unnumberedsubsec Gefechte, die über die Zeit entschieden werden

@c Das folgende Gefecht

@c @example
@c                 Schröder -- Kohl        4:5 /15
@c @end example

@c ist über die Zeit beendet worden.  Damit Felo weiß, auf wieviele Punkte
@c gefochten wurde, wird noch ein @samp{/15}
@c angehängt.@footnote{Fairerweise muß ich zugeben, daß dies ein Relikt aus
@c einer älteren Fassung des Programms ist.  Der aktuelle Algorithmus zur
@c Berechnung der Felo-Zahl nutzt diese Info gar nicht -- aber es kann bei
@c einer Änderung der Spielregeln für die Felo-Zahlen signifikant werden.
@c Beispielsweise kann lokal eine Fechtgruppe alle Gefechte gewichten nach
@c der Siegpunktzahl und nicht nach der Anzahl der gefochtenen Treffer.
@c Dafür muß sie zwar den Quellcode etwas modifizieren, aber dann wird
@c diese Info gebraucht.

@c Unter Freizeitfechtern ist das ohnehin nicht wichtig, weil es dort sehr
@c selten ist, daß ein Gefecht über die Zeit beendet wird.}

@unnumberedsubsec Einzelgefechte in einem Mannschaftsmatch

Es ist zwar auf den ersten Blick ein bißchen ungewöhnlich, aber jedes
Gefecht in einem Mannschaftsmatch ist ja auch ein Einzelgefecht -- wieso
also nicht auch zur Berechnung der Felo-Zahlen heranziehen.  Nun
passiert es dabei gerne mal (gerade unter Freizeitspielern), daß dabei
ein recht starker Fechter einen Anfänger haushoch von der Planche putzt.
Obwohl das aus mathematischer Sicht die Felo-Zahlen nicht unfair
beeinflußt, könnte das vom Anfänger als Grund angesehen werden, gar
nicht mitzumachen.  Deshalb kann man solche Team-Gefechte mit einem
@samp{*} markieren:

@example
2006-10-12.1    Anakin -- Elmer         5:0 *
           2    Wile Coyote -- Anakin   3:10*
           3    Wile Coyote -- Elmer    5:5 *
           4    Anakin -- Elmer         8:0 *
           5    Wile Coyote -- Anakin   3:10*
           6    Wile Coyote -- Elmer    3:5 *
@end example

@noindent
Solche Gefechte werden dann immer so gewichtet wie ein Gefecht
auf@tie{}5, egal, wie es ausgeht.  Da ein Team-Wettkampf ohnehin eigene
Regeln zu haben scheint, ist es vermutlich ganz generell sinnvoll, ihn
nicht zu hoch zu gewichten.

@unnumberedsubsec Fremdfechter und Gefechte in Fremdgruppen

Fremdfechter (super Begriff) sind Fechter, die nicht zur Gruppe gehören
(sondern zu einer anderen), aber mal für einen Trainigstag
vorbeischauen.  Oder es sind Fechter, denen man auf einem Turnier
begegnet.  Wie auch immer, sie haben zwar eine aktuelle Felo-Zahl,
werden aber nicht in der Datei geführt.  Sie dort einzutragen wäre
Blödsinn, weil sie beim nächsten Besuch eine andere Felo-Zahl haben
werden, die man ja nicht selber ausrechnen kann, weil sie in ihrem
Heimatverein zustande gekommen ist.

Trotzdem können und sollen sie in die Rechnung eingehen:

@example
2006-10-14      Anakin -- Riker <1764>      0:5
@end example

@noindent
Man gibt also ihre Felo-Zahl (bei der sie hoffentlich nicht mogeln) in
spitzen Klammern @samp{<...>} in die Gefechtzeile ein.  Man kann deren
Namen auch weglassen, Felo interessiert sich nur für die Zahl in den
spitzen Klammern.

Umgekehrt kann ein Fechter melden, daß er/sie gestern in einem
Fremdverein gegen einen 1453-er Fechter 15:11 gewonnen hat.  Das kann
man dann genauso eintragen.

Es ist übrigens gar nicht so blöd, Gefechte mit Fremdfechtern auch mit
einem @samp{*} zu markieren, siehe oben, weil ihre Felo-Zahl nicht so
vertrauenswürdig ist wie die der hauseigenen Fechter.  Einen großen
Unterschied macht das aber nicht.


@node Felo-Zahlen berechnen
@section Felo-Zahlen berechnen

Felo-Zahlen zu berechnen ist denkbar einfach.  Im Menü ,,Berechnen``
klickst du auf ,,Felo-Zahlen berechnen`` -- fertig.  Es öffnet sich ein
Fenster mit einer Tabelle der Felo-Zahlen aller Fechter.  Naja, fast
alle.  Neulinge, die noch keine Anfangs-Felo-Zahl haben, sind
ausgenommen, @pxref{Schätzen von Neueinsteigern}, ebenso wie Fechter, die
in Klammern stehen, also nicht genannt werden wollen.

@image{felo-screen-4-de,10cm,,Berechnete Felo-Zahlen}

Indem man auf ,,In die Zwischenablage kopieren`` klickt, wird die
Tabelle in einer Form in die Zwischenablage übernommen, die sich sehr
bequem in Word, Excel oder einem ähnlichen Programm einfügen läßt.  Und
dort kann man es noch ausschmücken, archivieren, ausdrucken etc.


@node Felo-Zahlen ins Internet stellen
@section Felo-Zahlen ins Internet stellen

Die einfachste Art, allen Fechtern in einer Gruppe ihre aktuellen
Felo-Zahlen mitzuteilen, ist per Webpage.  Nun kann ich hier nicht
erklären, wie man Webspace bekommt und wie man Dateien dorthin hochlädt,
wohl aber, wie Felo einen dabei unterstützen kann, die HTML-Seiten zu
erzeugen.

Man klickt im Menü ,,Berechnen`` auf ,,HTML erzeugen``.  Es öffnet sich
das folgende Dialogfenster:

@image{felo-screen-5-de,4cm,,HTML-Dateien erzeugen}

@noindent
Als erstes sollte man das Verzeichnis überprüfen, in dem die HTML-Datei
abgelegt wird.  Per Voreinstellung ist das dasselbe Verzeichnis, in dem
die Felo-Datei liegt.  Mit dem Parameter ,,Ausgabeordner`` kann man das
in der Felo-Datei aber auch direkt angeben.  Beispielsweise werden mit

@smallexample
Ausgabeordner           C:\Dokumente und Einstellungen\bronger\Eigene Dateien
@end smallexample

@noindent
die Web-Dateien im ,,Eigene-Dateien``-Ordner abgelegt.

Aber wieder zurück zum Dialogfenster oben.  Klicke ich dort auf
,,Okay``, dann wird die HTML-Datei mit der Ergebnisliste in das vorher
angegebene Verzeichnis geschrieben und -- falls man es ausgewählt hat --
zusätzlich eine Vorschau auf dem Bildschirm angezeigt.

Als besonderes Schmankerl ist es möglich, einen Plot hinzuzufügen, der
den zeitlichen Verlauf der Felo-Zahlen für jeden Fechter angibt.  So ist
es ein leichtes, zu sehen, wie man sich über die Wochen und Monate
entwickelt.  @strong{Achtung:} Damit das klappt, müssen Gnuplot,
Ghostscript und ImageMagick installiert sein, @pxref{Installation von
Zusatzprogrammen}.  Auf dem Bildschirmphoto unten kann man das volle
Programm der Vorschau sehen, also mit Plot.

Gleichzeitig nennt einem Felo in einem Extra-Fenster die Dateien, die
man auf den Webserver kopieren muß.

Die HTML-Datei bindet übrigens ein CSS-Stylesheet mit Namen
@file{felo.css} ein.  Ist es vorhanden, kann es das komplette Layout der
generierten Webseite verändern.  Ich kann das hier allerdings nicht
weiter erläutern, weil's zuviel wäre.  Benutzer, die CSS kennen, werden
auch wissen, was sie zu tun haben.

@image{felo-screen-6-de,8cm,,HTML-Preview mit Plot}


@node Bestimmen von Anfangs-Felo-Zahlen
@section Bestimmen von Anfangs-Felo-Zahlen

Es gibt zwei sehr unterschiedliche Situationen, in denen eine
Anfangs-Felo-Zahl geschätzt werden muß: Wenn die ganze Fechtegruppe
Felo-Zahlen verpaßt bekommen muß, und wenn später ein Neueinsteiger
dazukommt.

@menu
* Anfangs-Felo-Zahlen für die ganze Gruppe::  Das Bootstrapping.
* Schätzen von Neueinsteigern::  Wenn ein neuer dazukommt.
@end menu


@node Anfangs-Felo-Zahlen für die ganze Gruppe
@subsection Anfangs-Felo-Zahlen für die ganze Gruppe

Das Bestimmen der Start-Felo-Zahlen für eine Fechtergruppe ist der
einzige kniffelige Teil bei der Sache und meist das allererste, was man
mit dem Felo-Programm macht.  Aber es ist wichtig, denn das Felo-System
kann nur @emph{Änderungen} der Felo-Zahl nach Gefechten durchführen.
Irgendwo muß aber die allererste Felo-Zahl für jeden Fechter herkommen.

Ausgangspunkt ist also eine Gruppe von völlig Felo-jungfräulichen
Fechtern.  Irgendeiner in der Gruppe, der das Vertrauen aller genießt
@t{:-)}, muß nun alle Fechter mit @emph{vorläufigen} Anfangswerten
einschätzen.  Viel böses Blut sollte das nicht verursachen, weil das
Felo-Programm später ohnehin alles nochmal neu berechnen wird,
d.@s{}h.@: niemand muß diese Schätzung zu Gesicht bekommen.  Es geht bei
der Schätzung letztlich nur um die Einschätzung der mittleren
Spielstärke der ganzen Gruppe.

Ich empfehle, die Tabelle in Abschnitt @ref{Felo-Zahlen} als
Anhaltspunkt zu nehmen und nur auf 100@tie{}Punkte genau zu schätzen.
Dabei könnte beispielsweise herauskommen:

@example
Alexander          1600
Julia              1400
Christian          1600
Jens               1300
Max                1500
Georg              1500
Peter              1700
Christine          1400
Schorsch           1700
@end example

Die zweite wichtige Zutat sind Fechtergebnisse, je mehr, desto besser,
allerdings sollten sie nicht aus einem zu langen Zeitraum kommen.  So
fünf bis zehn Gefechte pro Fechter sollten es schon sein, verteilt auf
maximal ein halbes Jahr.  Es ist aber kein Beinbruch, wenn ihr diese
Bedingungen nicht streng erfüllt.  Die Fechtergebnisse gibt man ein und
führt das sogenannte @emph{Bootstrapping} durch.  Dabei berechnet das
Felo-Programm vollautomatisch die idealen Startwerte aus den
vorläufigen.

Dazu klickt man im Menü ,,Berechnen`` auf ,,Bootstrapping``:

@image{felo-screen-2-de,5cm,,Auf Bootstrapping klicken}

Danach klickt man nochmal auf ,,Ja`` und wartet einen kurzen Moment.
Die Anfangszahlen aller Fechter werden daraufhin in der Datei auf die
bestmöglichen Startwerte gesetzt, die sich aus den bisherigen Gefechten
ergeben.  Die Datei sollte man daraufhin speichern und die Startwerte
nie wieder anfassen, es sei denn, man weiß genau, was man tut.  Von da
an werden nur noch Gefechte (und neue Fechter) hinzugefügt.

Wenn ihr bislang noch keine Gefechte aufgeschrieben haben, könnt ihr
auch mit den von euch selber geschätzten Felo-Zahlen anfangen.  Dann müßt
ihr aber damit rechnen, daß die Zahlen in den ersten Wochen sich etwas
wild verhalten, weil sie erst noch ihren wahren Wert finden müssen.

Habt ihr hingegen schon @emph{sehr} viele Gefechte aufgeschrieben,
solltet ihr nur den ersten Teil davon (z.@s{}B. das erste halbe Jahr)
für das Bootstrapping verwenden.


@node Schätzen von Neueinsteigern
@subsection Schätzen von Neueinsteigern

Ein gänzlich anderes Problem ist, wenn ein neuer Fechter in die Gruppe
einsteigen möchte und er hat noch keine Felo-Zahl.  (Hätte der Neuling
schon eine aktuelle Felo-Zahl, wird die natürlich als Startwert
genommen.)  Bootstrapping kann man nicht machen, weil das ja alle
Startwerte verändern würde.  Es darf aber nur der Neuling (oder die
Neulinge) eine Anfangs-Felo-Zahl bekommen.

Das geht so: Der Fechter wird erst als ,,Neuling`` geführt, indem seine
Felo-Zahl von dir auf eine eine symbolische@tie{}`@math{0}' gesetzt
wird, um klarzumachen, daß er noch gar keine hat.  Nach
ca.@tie{}10@tie{}Gefechten auf 5@tie{}Treffer (oder z.@s{}B. 4
auf@tie{}15), kann das Felo-Programm einen Startwert schätzen.  Dazu
klickt man im Menü ,,Berechnen`` auf ,,Neulinge einschätzen``:

@image{felo-screen-3-de,5cm,,Neulinge einschätzen}

In diesem Fall hatte Obi Wan noch keine Felo-Zahl.  Nach dem ,,Neulinge
einschätzen`` wird eine Schätzung für seine Anfangs-Felo-Zahl
eingetragen.@footnote{Das muß nicht genau die sein, die sich dann für
ihn nach dem durchrechnen aller Gefechte ergibt, denn es ist ja nur
seine @emph{Anfangs-}Felo-Zahl.}  Falls die Zahl der Gefechte von
Obi@tie{}Wan noch nicht ausreicht, um eine Anfangszahl zu schätzen,
beläßt das Programm sie einfach auf@tie{}`@math{0}'.  Dann hat er eben
Pech gehabt und muß noch ein paar Trainigstage lang Ergebnisse
produzieren.


@node Liste aller Parameter
@section Liste aller Parameter

@unnumberedsubsec Allgemeine Parameter

@table @code

@item Gruppenname
Der Name der Gruppe, zu der diese Felo-Datei gehört.  Einen Fechtverein
teilt man sinnvollerweise in die Waffengattungen ein, d.@s{}h.@: für
jede Waffengattung eine Gruppe und damit eine Felo-Datei.  Mann kann
noch zusätzlich zwischen Männlein und Weiblein unterscheiden, aber da
wir in meinem Verein eh gemischt Fechten, haben wir das nicht gemacht.

Wenn der Gruppenname nicht angegeben wird, wird einfach der Dateiname
dafür genommen, also @file{florett.felo} enthält dann die Daten der
Gruppe ,,Florett``.

@end table

@unnumberedsubsec Plot-Parameter

Diese Parameter steuern das Aussehen des Plots bei der HTML-Ausgabe,
@pxref{Felo-Zahlen ins Internet stellen}.

@table @code

@item Ausgabeordner
Der Order, in dem die HTML-Dateien (und eventuell die Plot-Grafiken)
beim erzeugen einer Webseite abgelegt werden.  Per Voreinstellung ist
das derselbe Ordner, in dem auch die Felo-Datei liegt.

@item Plot-Tics Mindestabstand
Die Anzahl der Tage, die im Plot mindestens zwischen zwei Trainingstagen
liegen müssen, damit sie im Plot eine Beschriftung bekommen.  Das soll
verhindern, daß sich die Texte im Plot häßlich überlappen.
@emph{(Vorgabewert: 7)}

@item Plot Mindestdatum
Das Startdatum für den Plot, d.@s{}h.@: erst ab diesem Datum werden
Trainingstage in den Plot aufgenommen.  Das Format muß wie üblich
JJJJ-MM-TT sein.  @emph{(Vorgabewert: 1980-01-01)}

@item Plot maximale Tage
Die maximale Anzahl von Tagen (Kalendertage, nicht Trainingstage), die
in den Plot aufgenommen werden.  Das verhindert, daß der Zeitraum, der
durch den Plot abgedeckt wird, immer mehr anwächst und sich alles immer
dichter drängt.  @emph{(Vorgabewert: 366)}

@item Fechter pro Plot
Maximale Zahl von Fechtern in einem Plot.  @emph{(Vorgabewert: 30)}

@item Plot-Überlapp
Zahl der Fechter, die bei mehreren Plots in beiden benachbarten Plots
auftauchen.  @emph{(Vorgabewert: 5)}

@end table

Die folgenden Parameter sind nur unter Windows interessant.  Unter Linux
werden die Programme -- sofern sie installiert sind -- gewöhnlich ohne
Probleme gefunden.  Für Hinweise zur Installation dieser Programme
@pxref{Installation von Zusatzprogrammen}.

@table @code

@item Pfad von Gnuplot
Der vollständige Pfad zum Gnuplot-Programm.  Unter Windows heißt diese
Datei @file{wgnuplot.exe}.  Wenn Felo Gnuplot nicht findet, sagt es in
einer Fehlermeldung, wo es gesucht hat.

@item Pfad von convert
Der vollständige Pfad zum convert-Programm von ImageMagick.  Unter
Windows heißt diese Datei @file{convert.exe}.  Wenn Felo Gnuplot nicht
findet, sagt es in einer Fehlermeldung, wo es gesucht hat.

@end table

@unnumberedsubsec Parameter für die Schätzung von Anfangs-Zahlen

@table @code

@item 5er-Gefechte für Schätzung
Die Zahl der 5er-Gefechte, die ein Neuling bestritten haben muß, damit
Felo mit der Funktion ,,Berechnen`` -- ,,Neulinge einschätzen`` eine
Schätzung wagt, @pxref{Schätzen von Neueinsteigern}.  Diese Gefechtszahl
ist nur ein Richtwert, weil die genaue Zahl auch davon abhängt, wie
knapp die Gefechte ausgegangen sind.  Außerdem zählen Gefechte auf 10
oder 15 natürlich wie mehrere 5er-Gefechte.  @emph{(Vorgabewert: 10)}

@item Schwellwert Bootstrapping
Die Genauigkeit, die die Anfangs-Felo-Zahlen, die beim Bootstrapping
(@pxref{Anfangs-Felo-Zahlen für die ganze Gruppe}) berechnet werden,
mindestens haben müssen.  Scheitert das Bootstrapping, ist es sinnvoll,
diesen Wert zu erhöhen, z.@s{}B. um Faktor@tie{}10.  @emph{(Vorgabewert:
0.001)}

@end table

@unnumberedsubsec Detail-Parameter zur Berechnung der Felo-Zahlen

Die hier sollte man nur benutzen, wenn man wirklich weiß, was man tut.

@table @code

@item k-Faktor Top-Fechter
Der k-Faktor, der bei der Berechnung der Felo-Zahlen für sehr gute
Fechter zugrunde gelegt wird.  @emph{(Vorgabewert: 25)}

@item Felo-Zahl Top-Fechter
Die Mindest-Felo-Zahl, ab der man als Top-Fechter bei der
Felo-Zahl-Berechnung gilt.  Es geht hier also nur um die Festsetzung des
richtigen k-Faktors.  @emph{(Vorgabewert: 2400)}

@item k-Faktor Rest
Der k-Faktor, der bei der Berechnung der Felo-Zahlen für normale
Fechter zugrunde gelegt wird.  @emph{(Vorgabewert: 32)}

@item k-Faktor Neulinge
Der k-Faktor, der bei der Berechnung der Felo-Zahlen für Neulinge
zugrunde gelegt wird.  Hier geht es also um Neulinge, für die eine
Anfangs-Felo-Zahl schon bestimmt wurde (von Hand oder mit dem Programm),
die aber dennoch erst ihre ersten Gefechte bestreiten.
@emph{(Vorgabewert: 40)}

@item 5er-Gefechte Neulinge
Die Zahl der 5er-Gefechte, die ein Neuling bestritten haben muß, um bei
der Bestimmung des k-Faktors nicht mehr als Neuling zu gelten.  Diese
Gefechtszahl ist nur ein Richtwert, weil die genaue Zahl auch davon
abhängt, wie knapp die Gefechte ausgegangen sind.  Außerdem zählen
Gefechte auf 10 oder 15 natürlich wie mehrere 5er-Gefechte.  @emph{(Vorgabewert:
15)}

@item Minimum Felo-Zahl
Die Felo-Zahl, unter die man nicht rutschen kann.  Würde nach einem
verlorenen Gefecht die Felo-Zahl unter dieses Minimum fallen, wird sie
genau auf dieses Minimum gesetzt.  @emph{(Vorgabewert: 1200)}

@item Gewichtung von Team-Gefechten
Einzelgefechte im Rahmen eines Team-Wettkampfes werden nicht wie normale
Gefechte gewichtet, wenn sie mit @samp{*} markiert wurden,
@pxref{Zusatz-Infos zum Eingeben von Gefechten}.

Normalerweise wird ein 15:14 nämlich stärker gewichtet als ein 15:0.
Bei Teamwettkämpfen wird -- letztlich aus psychologischen Gründen, weil
Anfänger da gerne mal 17:0 abgestraft werden -- jedes Gefecht gleich
gewichtet.  Dieses Parameter gibt an, wievielen typischen 5er-Gefechten
ein solches Gefecht bei der Gewichtung entsprechen soll.
@emph{(Vorgabewert: 1.0)}

@end table


@node Installation
@chapter Installation

@menu
* Installation unter Windows::  Das, was wirklich wichtig ist.
* Installation von Zusatzprogrammen::  Nur wenn man Plots braucht.
* Installation unter Linux::    
@end menu


@node Installation unter Windows
@section Installation unter Windows

Als erstes lädt man sich das Programm von
@uref{http://sourceforge.net/project/showfiles.php?group_id=183431&package_id=212989,
der Projektseite auf Sourceforge} als EXE-Datei herunter und startet
diese.  Es gibt dabei zwei Möglichkeiten.  Entweder man tut das als
@emph{Administrator}.  In diesem Fall wird Felo für @emph{alle} Benutzer
installiert.  Oder man startet die EXE-Datei, während man als
@emph{normaler Benutzer} eingeloggt ist.  Dann wird Felo nur für diesen
Benutzer installiert.

Ansonsten ist die Installation puppeneinfach.  Es sollte reichen, ein
paar Mal auf ,,Okay`` zu klicken.  Übrigens geht die De-Installation
genauso leicht.  Du mußt nur aufpassen, als derselbe Benutzer/Admin wie
bei der Installation eingeloggt zu sein, ansonsten könnte es passieren,
daß Felo nicht restlos entfernt wird.

Wenn du kein Interesse daran hast, auch grafische Plots mit den
Felo-Zahlen der Fechtgruppe zu machen, kannst du den Rest dieses
Kapitels überspringen.


@node Installation von Zusatzprogrammen
@section Installation von Zusatzprogrammen

Die folgenden drei kostenlosen Zusatzprogramme werden nur benötigt, wenn
man auch grafische Plots, die den zeitlichen Verlauf der Felo-Zahl
darstellen, haben möchte.

@subheading Gnuplot

Als ersten muß man sich
@uref{http://sourceforge.net/project/showfiles.php?group_id=2055&package_id=1996,Gnuplot
als ZIP-Datei} herunterladen.  Der Dateiname ist @file{gp400win32.zip},
wobei @file{400} die Versionnummer ist.  Diese ZIP-Datei entpackt man am
besten in das Verzeichnis @file{C:\Programme\gnuplot}.


@subheading Ghostscript

Ghostscript kann man auf dem
@uref{ftp://mirror.cs.wisc.edu/pub/mirrors/ghost/GPL/gs854/,FTP Mirror
für Ghostscript} herunterladen (man braucht die EXE-Datei).  Es ist
wichtig, daß man diese Datei als Administrator ausführt!

@subheading ImageMagick

Auf der @uref{http://www.imagemagick.org,Homepage von ImageMagick}
klickt man links auf ``Binary Releases'' -- ``Windows'', lädt dann eine
der dort angebotenen EXE-Dateien herunter und startet sie (möglichst als
Administrator).


@node Installation unter Linux
@section Installation unter Linux

Das Programm ist in zwei Varianten für Linux auf der
@uref{http://sourceforge.net/project/showfiles.php?group_id=183431, der
Projektseite auf Sourceforge} verfügbar, nämlich als RPM und als
Tar-Ball.  Das RPM enthält als einzige Abhängigkeit Python, obwohl das
nicht ganz richtig ist.  Man benötigt zusätzlich
@uref{http://www.wxpython.org/,wxPython}, was allerdings kein Problem
sein sollte, weil es längst eine Standard-Erweiterung von Python
darstellt.

Will man zusätzlich Plots drucken, ist man von denselben drei Programmen
abhängig wie die Windows-Benutzer, also
@uref{http://www.gnuplot.info,Gnuplot},
@uref{http://www.cs.wisc.edu/~ghost/,Ghostscript} und
@uref{http://www.imagemagick.org,ImageMagick}.  Sollte aber ebenso kein
Problem sein.


@node Felo-Zahlen -- etwas Hintergrund
@chapter Felo-Zahlen -- etwas Hintergrund

@menu
* Die Berechnung der Felo-Zahl::  
* Globales Vergleichen von Felo-Zahlen::  
* Felo und andere Sportarten::  
* Felo für Programmierer::      
@end menu


@node Die Berechnung der Felo-Zahl
@section Die Berechnung der Felo-Zahl

Die Berechnung der neuen Felo-Zahl geschieht in drei Schritten:

@enumerate
@item
Es wird der Resultatwert für den Fechter berechnet.  Das ist der Anteil
der Einzeltreffer, die er gesetzt hat.  Beispiel: Gewinnt der Fechter
15:10, ist der Resultatwert @math{15/(15+10)=0.6}.

@item
Dann wird aus der Differenz der Felo-Zahlen beider Fechter der
@emph{erwartete} Resultatwert berechnet.  Die Formel dazu findet man
z.@s{}B. im
@uref{http://de.wikipedia.org/wiki/Elo-Zahl#Berechnung,Wikipedia-Artikel zur
Elo-Zahl}.

@item
Die Differenz zwischen Resultat und erwartetem Resultat nenne ich mal
die @emph{Überraschung}.  Die Überraschung wird nun multipliziert mit
der Zahl der Einzeltreffer des Gefechts und zur alten Felo-Zahl
addiert.  Das ergibt die neue Felo-Zahl des Fechters.
@end enumerate

Um genau zu sein, wird die Überraschung auch mit dem sogenannten
@emph{k-Faktor} multipliziert, @pxref{Liste aller Parameter}.  Das hört
sich geheimnisvoller an, als es ist.  Der k-Faktor bestimmt, wie stark
sich die Felo-Zahlen ändern.  Ist er zu groß, wackeln die Felo-Zahlen zu
stark hin und her.  Ist er zu klein, dauert es zu lange, bis sich die
Felo-Zahl eines Fechter auf der wahren Spielstärke eingependelt hat.

@subheading Warum wird auch das Ergebnis berücksichtigt?

Klassischerweise kommt es beim Fechten nur auf Sieg oder Niederlage an.
Es scheint daher auf den ersten Blick ungewöhnlich, eventuell sogar
irritierend, daß die Felo-Zahlen auch das Ergebnis berücksichtigen.

Der Grund ist ganz einfach: Sie konvergieren so schneller, d.@s{}h.@:
sie finden so viel schneller ihren korrekten Wert.  Das ist insbesondere
dann günstig, wenn eine Fechtergruppe ganz neu mit Felo-Zahlen anfängt.
Es ist aber auch gut, um die @emph{aktuelle} Fechtstärke anzugeben.  Ist
man mal über einen gewissen Zeitraum ein bißchen besser in Form, geht
die Felo-Zahl rauf.  Würde sie nur Siege und Niederlagen
berücksichtigen, kann es gut sein, daß das einer solchen Felo-Zahl
entgeht.

Man kann eine reine Sieg/Niederlage-Felo-Zahl einfach dadurch
realisieren, daß man die Punktzahl des Verlierers in der Felo-Datei auf
Null setzt:

@smallexample
2006-05-01      Anakin -- Elmer         5:0
                Anakin -- Wile Coyote   5:0
                Elmer -- Wile Coyote    5:0
                Elmer -- Anakin         0:5
                Wile Coyote -- Anakin   0:5
                Elmer -- Wile Coyote    0:10
                Anakin -- Wile Coyote   0:10
@end smallexample

@noindent
Allerdings sind die sich daraus ergebenen Felo-Zahlen nicht mehr ganz
vergleichbar mit denen anderer Fechtgruppen, also aufgepaßt!  Außerdem
ändert sich an der Rangfolge kaum etwas.  Man verliert viel und gewinnt
wenig, daher rate ich davon ab.

Die Felo-Zahlen, so wie sie sind, sind eine gute Kombination aus rascher
Anpassung und akkurater Einschätzung.


@node Globales Vergleichen von Felo-Zahlen
@section Globales Vergleichen von Felo-Zahlen

Felo-Zahlen können nur Fechter innerhalb einer Fechtgruppe @emph{relativ}
vergleichen.  Damit man auch zwischen Gruppen vergleichen kann
(z.@s{}B. zwischen zwei Vereinen), muß man bei der 
Einschätzung der Anfangs-Felo-Zahlen (@pxref{Anfangs-Felo-Zahlen für die
ganze Gruppe}) sehr realistisch und sorgfältig vorgegangen sein.  Nun
gebe ich zu, daß Angaben wie ,,starke Freizeitspieler`` ziemlich
schwammig sind, deshalb ist das nur begrenzt realistisch.  Ein ganz
gutes Vergleichen sollte dennoch möglich sein.

Wesentlich besser ist es natürlich, wenn ein paar Fechter in beiden
Gruppen fechten.  Sie verbinden quasi die Felo-Zahlen beider Gruppen und
machen sie so vergleichbar.  Man kann dafür beide Gruppen zu einer
zusammenlegen.  Theoretisch reicht ein einzelner Fechter dafür aus, aber
der hat dann viel zu tun.  Wurde eine der beiden Fechtgruppen zu gut
bewertet, schaufelt er dann quasi die Punkte zur anderen Gruppe, bis
alles stimmig ist.

Man kann dazu natürlich auch die vielen Fechtturniere benutzen, ist aber
viel Arbeit: Man sammelt die Felo-Zahlen aller Fechter, gegen die die
eigenen Leute fechten @emph{und} die überhaupt eine Felo-Zahl haben,
ein.

Wie auch immer, es gibt leider noch zu wenig Erfahrung mit Felo-Zahlen,
um zu wissen, wie gut man Gruppen Felo-technisch durch gemeinsame
Fechter und/oder Turniere verbinden kann (so gut sie auch innerhalb
einer Gruppe funktionieren).

Übrigens lassen sich verschiedene Waffengattungen nie richtig
miteinander verbinden, weil sie ja nie gegeneinander fechten können.  Da
ist man dann allein auf die realistische Einschätzung angewiesen.


@node Felo und andere Sportarten
@section Felo und andere Sportarten

Kann man das Felo-Programm auch in anderen Sportarten einsetzen?

Ja, man kann, allerdings funktionieren Teamsportarten nicht so gut.
Auch bei Sportarten, bei denen die Zeit ein Match beendet, funktioniert
es nicht so dolle.

Was Teamsportarten angeht, klappt Felo gar nicht, wenn man eine fixe
Gruppe aus @math{x}@tie{}Personen hat, aus denen an jedem Trainigstag
zwei beliebige Mannschaften zusammengestellt werden.  Wie soll man das
auch eintragen.  Nur, wenn man @math{x}@tie{}@emph{Teams} hat, die immer
aus den mehr oder weniger gleichen Leuten bestehen, kann man die Teams
als Sportler führen und ihre Ergebnisse aufschreiben.  Das schränkt die
Brauchbarkeit von Felo zugegebenermaßen deutlich ein, insbesondere im
Freizeitsport.

Bei Sportarten, die über die Zeit entschieden werden, kann man nur die
drei möglichen Ergebnisse 1:0, 0:1 und 1:1 benutzen, für Sieg,
Niederlage und unentschieden.  Allerdings fällt mir jetzt spontan keine
solche Sportart ein, die nicht auch eine Mannschaftssportart wäre.

Für alle anderen Sportarten mit einem Sportler-Sportler-Duell,
z.@s{}B. Tennis, Badminton, Tischtennis, Armdrücken, Wettblinzeln oder
Ostereiertitschen, gibt es an sich keine Schwierigkeiten.  Existiert
kein richtiger Endstand sondern nur Sieger und Verlierer (oder
unentschieden), dann siehe oben, ansonsten trägt man eben das Ergebnis
ein.

Es ist übrigens nicht so wichtig, ob man bei Sportarten mit Sätzen die
Sätze, Spiele oder Punkte als Grundlage nimmt.  Groß wird der
Unterschied nicht sein.  Beim Tennis kann man ein 6:4@tie{}6:3 entweder
als 2:0 oder als 12:7 eintragen.  (Man kann auch die Einzelpunkte
zählen, wenn man zuviel Zeit hat.)  Grundsätzlich gilt natürlich: Je
feiner, desto besser.


@node Felo für Programmierer
@section Felo für Programmierer

Dieser Abschnitt ist für Programmierer gedacht, die Felo in eigenen
Programmen benutzen wollen.

Eine grafische Bedienoberfläche ist nett, aber mit der kann man kaum
etwas automatisieren.  Beispielsweise ist es damit unmöglich, die
aktuellen Felo-Zahlen einer Fechtergruppe in eine bestehende Webseite
perfekt zu integrieren.  Insbesondere kann man mit dem
Standard-Felo-Programm nicht die Zahlen von Florett- und Degenfechtern
auf @emph{einer} Web-Seite unterbringen.

Für die meisten wird das kein Beinbruch sein, aber wer die totale
Kontrolle haben möchte, bekommt sie, und zwar gleich auf zwei
verschiedene Arten.

Zum einen kann man das Python-Modul @file{felo_rating.py} als
Kommandozeilen-Programm aufrufen.  Ich gebe hier mal nur den Hilfe-Text
dieses Programms an:

@example
Aufruf: felo_rating.py [Optionen]

Optionen:
  -h, --help            Zeige diese Meldung und beende das Programm
  -p, --plots           Erzeuge Plots der Felo-Zahlen
  -b, --bootstrap       Versuche, gute Start-Felo-Zahlen fuer alle zu
                        berechnen
  --max-cycles=NUMMER   Maximale Iterationsschritte beim Bootstrapping.
                        Default: 1000
  --estimate-freshmen   Versuche, Neueinsteiger zu bewerten
  --write-back          Schreibe die neuen Startzahlen zurueck in die Felo-
                        Datei
  --version             Zeige Versionsnummer und Lizenz-Informationen
  -o DATEINAME, --output=DATEINAME
                        Name der Ausgabedatei.  Default: Ausgabe auf dem
                        Bildschirm (stdout)
@end example

@noindent
Wer Felo als GUI-Programm einigermaßen verstanden hat, wird wissen, was
die einzelnen Optionen bedeuten.  Selbstverständlich ist das
Eingabeformat genau dasselbe Dateiformat wie in der GUI-Version.  Das
Ausgabeformat ist recht simpel und kann von einem eigenen Programm
eingelesen werden.

Zum anderen kann man auch direkt in Python ein eigenes Programm
schreiben und @file{felo_rating.py} als Modul einbinden.  Man kann dann
@uref{http://felo.sourceforge.net/api/,Felos API} nutzen, um eigene
Programme mit Felo-Zahlen zu schreiben.

@c  LocalWords:  Felo Elo copyright email quotation acronym end copying title
@c  LocalWords:  finalout titlepage subtitle value image felo logo author page
@c  LocalWords:  vskip filll insertcopying dircategory Miscellaneous direntry
@c  LocalWords:  iftex hyphenation logue logues ifnottex node top tie uref menu
@c  LocalWords:  ifhtml the table contents beginning chapter asis item section
@c  LocalWords:  EXE emph puppeneinfach Admin ref Gnuplot Ghostscript file win
@c  LocalWords:  subsection zip gnuplot Tar screen enumerate noindent strong
@c  LocalWords:  samp JJJJ cartouche Tabstopps key Tab example Elmer Wile math
@c  LocalWords:  Coyote unnumberedsubsec Info super Riker xref smallexample Obi
@c  LocalWords:  bronger Schmankerl Extra Schorsch Wan code Weiblein florett
@c  LocalWords:  Tics Mindestdatum wgnuplot exe convert pdf pxref Mindest dolle
@c  LocalWords:  Wettblinzeln Ostereiertitschen rating help plots bootstrap max
@c  LocalWords:  fuer cycles estimate freshmen write back zurueck version
@c  LocalWords:  output stdout Roberto Pereira
